### PR TITLE
Eagerly start and initialize EventsService before EventSourcedRegistryStorage

### LINKED ISSUE #3482: Event sourcing not publishing any data
Hi team.

Not sure whether this is a bug or just a misconfiguration on my end. 

I have configured Apicurio Event Sourcing [based on the docs](https://www.apicur.io/registry/docs/apicurio-registry/2.4.x/getting-started/assembly-configuring-the-registry.html#registry-cloud-events_registry). However, whenever I do an action in the registry (create/delete/update an artifact, or anything else), no data is published. I see no logs of event being fired on Apicurio side, and using kcat to tail the topic, no data is published on the topic I specified.

I am running the stack on my local machine via Docker. Apicurio version is 2.4.2.Final using the KafkaSQL distribution. This is my docker-compose configuration for the Apicurio Registry:

```yaml
schema-registry:
    image: apicurio/apicurio-registry-kafkasql:2.4.2.Final
    ports:
      - "8087:8087"
    environment:
      HTTP_PORT: 8087
      registry.kafkasql.bootstrap.servers: kafka:9092
      registry.rules.global.compatibility: FULL_TRANSITIVE
      registry.rules.global.validity: SYNTAX_ONLY
      registry.rest.artifact.deletion.enabled: "true"
      registry.events.kafka.config.bootstrap.servers: kafka:9092
      registry.events.kafka.topic: registry-events
```

On startup, I can see the Sink subscribing to the Kafka Sink:

```
INFO <_> [io.apicurio.registry.events.EventsServiceImpl] (main) Subscribing sink Kafka Sink 
```

I also tried to do the HTTP configuration, and I got the same behavior: nothing happened.

With the DEBUG log level enabled, this is the output I get:

```
 2023-06-30 22:46:28 DEBUG <> [io.apicurio.registry.storage.impl.kafkasql.KafkaSqlRegistryStorage] (KSQL Kafka Consumer Thread) Consuming 1 journal records.
 2023-06-30 22:46:28 DEBUG <> [io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink] (KSQL Kafka Consumer Thread) Processing Kafka message with UUID: 93ec9a26-a73d-4592-96c3-e0ae797bc9b7
 2023-06-30 22:46:28 DEBUG <_> [io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink] (KSQL Kafka Consumer Thread) Clearing tenant id after message processed
 2023-06-30 22:46:28 DEBUG <> [io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink] (KSQL Kafka Consumer Thread) Kafka message successfully processed. Notifying listeners of response.
 2023-06-30 22:46:28 DEBUG <> [io.apicurio.registry.storage.impl.kafkasql.KafkaSqlRegistryStorage] (KSQL Kafka Consumer Thread) Consuming 1 journal records.
 2023-06-30 22:46:28 DEBUG <> [io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink] (KSQL Kafka Consumer Thread) Processing Kafka message with UUID: 7339073d-efd4-46f5-9a49-6bcb9c02cbdb
 2023-06-30 22:46:28 DEBUG <_> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (KSQL Kafka Consumer Thread) Inserting an artifact row for: null 7c8458c9-7a6c-4aaa-85ae-518b8166e685
 2023-06-30 22:46:28 DEBUG <_> [io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink] (KSQL Kafka Consumer Thread) Clearing tenant id after message processed
 2023-06-30 22:46:28 DEBUG <> [io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink] (KSQL Kafka Consumer Thread) Kafka message successfully processed. Notifying listeners of response.
 2023-06-30 22:46:28 INFO <_> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-4) apicurio.audit action="createArtifact" result="success" src_ip="172.22.0.1" artifact_id="default" 
 2023-06-30 22:46:28 DEBUG <_> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (executor-thread-4) Getting a list of all artifact rules for: null 7c8458c9-7a6c-4aaa-85ae-518b8166e685
 2023-06-30 22:46:28 DEBUG <_> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (executor-thread-11) Selecting artifact (latest version) meta-data: null 7c8458c9-7a6c-4aaa-85ae-518b8166e685 (behavior = SKIP_DISABLED_LATEST)
 2023-06-30 22:46:28 DEBUG <_> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (executor-thread-10) Selecting artifact (latest version) meta-data: null 7c8458c9-7a6c-4aaa-85ae-518b8166e685 (behavior = SKIP_DISABLED_LATEST)
 2023-06-30 22:46:28 DEBUG <_> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (executor-thread-9) Searching for versions of artifact null 7c8458c9-7a6c-4aaa-85ae-518b8166e685
```

Steps to reproduce would be run Apicurio Registry with above configuration while running a Kafka cluster, do any relevant operation (create new artifact, for example), and see no data being published to the topic.

Please let me know if you need any extra information from my side, glad to assist.

### PR DESCRIPTION
**Pull request by andreaTP**
Following these docs: https://quarkus.io/guides/cdi-reference#startup_event
I ended up with this implementation that seems to work reliably.
Happy to receive better advice if I missed a Quarkus CDI nuance, cc. @carlesarnal 

Fix #3482

### CODE REVIEW

File: app/src/main/java/io/apicurio/registry/events/EventsServiceImpl.java [hunk 1]
```diff
@@ -36,12 +37,14 @@
 /**
  * @author Fabian Martinez
  */
+@Startup
```
Comment (carlesarnal) [inline app/src/main/java/io/apicurio/registry/events/EventsServiceImpl.java:40]: Actually, there is no difference between annotating a bean with this and observing the startup event like we're doing (when you annotate the bean with Startup a synthetic observer is created). +1 to the eager initialization, but this annotation is not required.

Comment (carlesarnal) [reply app/src/main/java/io/apicurio/registry/events/EventsServiceImpl.java:40]: Another possibility is to listen to the storage-ready event instead of waiting for the startup event like we're doing in the [KafkaSql](https://github.com/Apicurio/apicurio-registry/blob/main/storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlRegistryStorage.java#L195) storage since no events are gonna be fired if the storage has not been configured therefore there is no need to configure the sinks. Anyway, up to you, both approaches should work.

Comment (andreaTP) [reply app/src/main/java/io/apicurio/registry/events/EventsServiceImpl.java:40]: Tested removing the `Startup` annotation and the mechanism doesn't work somehow ...
It feels a little strange having to rely on `KafkaSQL storage` as it's not directly involved in this race condition.

Comment (andreaTP) [reply app/src/main/java/io/apicurio/registry/events/EventsServiceImpl.java]: as agreed, moved to `@PostConstruct`
