### PR TITLE
fix unit test

### LINKED ISSUE #635: Unit tests broken for streams storage
This kind of blocks #446 
Steps to reproduce it (run unit tests of streams storage variant) :
```
mvn clean install -DskipTests -Pstreams
mvn verify -pl storage/streams/ -Dtest=SerdeMixTest#testVersions -Pstreams
```
```
[ERROR]   SerdeMixTest.testVersions:63 » RestClient No artifact with ID 'GlobalId: 0' wa...
[ERROR]   SerdeMixTest.testVersions:63 » RestClient No artifact with ID 'GlobalId: 65536...
```

### PR DESCRIPTION
**Pull request by famartinrh**
Fixes #635

### CODE REVIEW

File: app/src/test/java/io/apicurio/registry/SerdeMixTest.java [hunk 1]
```diff
@@ -57,9 +57,10 @@ public void testVersions(Supplier<RegistryService> supplier) throws Exception {
         Schema schema = new Schema.Parser().parse("{\"type\":\"record\",\"name\":\"myrecord5\",\"fields\":[{\"name\":\"bar\",\"type\":\"string\"}]}");
         int id = confClient.register(subject, schema);
         confClient.reset();
-        
+
         this.waitForArtifact(subject);
 
+        this.waitForGlobalId(id);
```
Comment (EricWittmann) [inline app/src/test/java/io/apicurio/registry/SerdeMixTest.java:63]: What does waiting for the global id accomplish that waiting for the artifact doesn't?

Comment (famartinrh) [reply app/src/test/java/io/apicurio/registry/SerdeMixTest.java:63]: for some reason the `confClient.getById(id);` fails if you don't wait

Comment (EricWittmann) [reply app/src/test/java/io/apicurio/registry/SerdeMixTest.java:63]: @carlesarnal Can you verify this locally?  Also if you could try it with line 61 removed as well.  I don't see why we would need both of these waits.

Comment (carlesarnal) [reply app/src/test/java/io/apicurio/registry/SerdeMixTest.java:63]: Hi @famartinrh , @EricWittmann, makes sense that we need to add here the `waitForGlobalId` since the id argument of the `getById` operation is a global id. I'm not sure about the `waitForArtifact` but, I guess that we need it since we are trying to perform an `updateArtifact` operation that otherwise might fail.

Comment (EricWittmann) [reply app/src/test/java/io/apicurio/registry/SerdeMixTest.java:63]: Thanks @carlesarnal

**Comment by EricWittmann** [comment]
I'll leave both for now, even though I think we **should** only need the wait-for-globalId line.  But it won't hurt to have both.
